### ISSUE TITLE
Gerenciamento de ordens de serviço

### ISSUE THREAD

**Issue by rafatosta** [yasmincsme/EXA863_management_system_2023#1]
Implementar as funcionalidades referente à ordem de serviço.

Obs.: Métodos além do CRUD como: alocar a próxima ordem em aberto, etc.

**Comment by yasmincsme** [comment]
Para solucionar o problema, adicionei os métodos "findOpenWorkOrders()" e "getFirstOpenedWorkOrder()".  :white_check_mark:
